package Assignment1;

import Assignment1.gen.Assignment1.ccLexer;
import Assignment1.gen.Assignment1.ccParser;
import Assignment1.gen.Assignment1.ccVisitor;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.AbstractParseTreeVisitor;
import org.antlr.v4.runtime.tree.ParseTree;

import java.io.IOException;

public class main {
    public static void main(String[] args) throws IOException{

        // we expect exactly one argument: the name of the input file
        if (args.length!=1) {
            System.err.println("\n");
            System.err.println("cc Interpreter\n");
            System.err.println("=================\n\n");
            System.err.println("Please give as input argument a filename\n");
            System.exit(-1);
        }
        String filename=args[0];

        // open the input file
        CharStream input = CharStreams.fromFileName(filename);
        //new ANTLRFileStream (filename); // depricated

        // create a lexer/scanner
        ccLexer lex = new ccLexer(input);

        // get the stream of tokens from the scanner
        CommonTokenStream tokens = new CommonTokenStream(lex);

        // create a parser
        ccParser parser = new ccParser(tokens);

        // and parse anything from the grammar for "start"
        ParseTree parseTree = parser.start();

        // Construct an interpreter and run it on the parse tree
        Interpreter interpreter = new Interpreter();
        Double result=interpreter.visit(parseTree);
        System.out.println("The result is: "+result);
    }
}

// We write an interpreter that implements interface
// "ccVisitor<T>" that is automatically generated by ANTLR
// This is parameterized over a return type "<T>" which is in our case
// simply a Double.

class Interpreter extends AbstractParseTreeVisitor<Double> implements ccVisitor<Double> {
    @Override
    public Double visitStart(ccParser.StartContext ctx) {
        return null;
    }

    @Override
    public Double visitHardware(ccParser.HardwareContext ctx) {
        return null;
    }

    @Override
    public Double visitInput(ccParser.InputContext ctx) {
        return null;
    }

    @Override
    public Double visitOutput(ccParser.OutputContext ctx) {
        return null;
    }

    @Override
    public Double visitLatch(ccParser.LatchContext ctx) {
        return null;
    }

    @Override
    public Double visitLatches(ccParser.LatchesContext ctx) {
        return null;
    }

    @Override
    public Double visitUpdate(ccParser.UpdateContext ctx) {
        return null;
    }

    @Override
    public Double visitUpdates(ccParser.UpdatesContext ctx) {
        return null;
    }

    @Override
    public Double visitSimulate(ccParser.SimulateContext ctx) {
        return null;
    }

    @Override
    public Double visitSimulations(ccParser.SimulationsContext ctx) {
        return null;
    }

    @Override
    public Double visitNot(ccParser.NotContext ctx) {
        return null;
    }

    @Override
    public Double visitVariable(ccParser.VariableContext ctx) {
        return null;
    }

    @Override
    public Double visitParathesis(ccParser.ParathesisContext ctx) {
        return null;
    }

    @Override
    public Double visitConstant(ccParser.ConstantContext ctx) {
        return null;
    }

    @Override
    public Double visitBoolOr(ccParser.BoolOrContext ctx) {
        return null;
    }

    @Override
    public Double visitBoolAnd(ccParser.BoolAndContext ctx) {
        return null;
    }

    @Override
    public Double visitAllocate(ccParser.AllocateContext ctx) {
        return null;
    }
    // todo - Java will complain that "Interpreter" does not in fact
    // implement "ccVisitor" at the moment.

    /*public Double visitStart(ccParser.StartContext ctx){
        System.out.println("Evaluating Start");
        return visit(ctx.e);
    }
    public Double visitAdd(ccParser.AddContext ctx){
        Double d1=visit(ctx.e1);
        Double d2=visit(ctx.e2);
        System.out.println("Addition "+d1+ctx.op.getText()+d2);
        if (ctx.op.getText().equals("+"))
            return d1+d2;
        else return d1-d2;
    };
    public Double visitMult(ccParser.MultContext ctx){
        Double d1=visit(ctx.e1);
        Double d2=visit(ctx.e2);
        System.out.println("Mult "+d1+ctx.op.getText()+d2);
        if (ctx.op.getText().equals("*"))
            return d1*d2;
        else return d1/d2;
    }
    public Double visitVar(ccParser.VarContext ctx){
        System.err.println("Variables not yet supported.");
        System.exit(-1);
        return null;
    };
    public Double visitConst(ccParser.ConstContext ctx){
        return Double.valueOf(ctx.f.getText());
    }
    public Double visitParen(ccParser.ParenContext ctx){
        System.out.println("Parentheses");
        return visit(ctx.e);}*/




}

